### ISSUE TITLE
Icons difficult to discern on retina displays

### ISSUE THREAD

**Issue by squk** [ThePat02/BehaviourToolkit#4] opened 2023-11-09 00:14 UTC
<img width="343" alt="image" src="https://github.com/ThePat02/BehaviourToolkit/assets/3443591/fe0f80a3-cb6a-4604-bf9c-eb34537811ff">
Compared to the screenshots in the readme and the standard godot icons, these are appearing very small on my MacBook Pro (14-inch, 2021)

**Comment by ThePat02** [comment] 2023-11-09 10:50
That is indeed very weird, as the icons should be the same size as the original Godot icons! How about the Editor UI? Are the icons on the buttons also scaled down?

**Comment by ThePat02** [comment] 2023-11-09 11:09
The problem was probably caused by a missing import flag for editor scaling and should be fixed with PR #5 

@squk Please report back if this fixes things for you!

**Closed** 2023-11-09 11:09 UTC
Labels: bug
